[project]
name = "perlin-noise"
version = "0.1.0"
description = "2D Perlin noise implementation built from scratch in Python."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.4.6",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
